services:
  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped

  waha:
    image: devlikeapro/waha:latest
    environment:
      WHATSAPP_SWAGGER_USERNAME: ${WAHA_USER}
      WHATSAPP_SWAGGER_PASSWORD: ${WAHA_PASS}
      WAHA_DASHBOARD_USERNAME: ${WAHA_USER}
      WAHA_DASHBOARD_PASSWORD: ${WAHA_PASS}
      WAHA_API_KEY: ${WAHA_PASS}
      WAHA_WEBHOOK_URL: ${WAHA_WEBHOOK_URL}
      WHATSAPP_DEFAULT_ENGINE: ${WAHA_ENGINE}
      WHATSAPP_START_SESSION: ${WAHA_SESSION_NAME}
      WHATSAPP_HOOK_SESSION_START: "true"
      WHATSAPP_RESTART_ALL_SESSIONS: "true"
      WAHA_AUTO_START_DELAY_SECONDS: "3"
      WAHA_HOST: "0.0.0.0"
    volumes:
      - waha_media:/app/.media
      - waha_sessions:/app/.sessions
      - ./start-waha-with-config.sh:/start-waha-with-config.sh
    ports:
      - "3000:3000"
    command: /start-waha-with-config.sh
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    environment:
      WEBHOOK_URL: ${N8N_WEBHOOK_URL}
      N8N_HOST: ${N8N_HOST}
      GENERIC_TIMEZONE: America/Sao_Paulo
    volumes:
      - n8n_data:/home/node/.n8n
    ports:
      - "5678:5678"
    restart: unless-stopped
    depends_on:
      - whisper-asr

  whisper-asr:
    image: onerahmet/openai-whisper-asr-webservice:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - ASR_MODEL=${ASR_MODEL}
      - LANGUAGE=pt
      - WHISPER_THREADS=4

volumes:
  waha_sessions:
  waha_media:
  n8n_data:
